# Generated by Django 4.2 on 2023-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('OPEN_MIC', 'OPEN_MIC'), ('SUFI_NIGHT', 'SUFI_NIGHT'), ('BATTLE_OF_BANDS', 'BATTLE_OF_BANDS'), ('STUDENT_OF_THE_YEAR', 'STUDENT_OF_THE_YEAR'), ('VOICE_OF_HBTU', 'VOICE_OF_HBTU'), ('AWAKENINGS_DJ', 'AWAKENINGS_DJ'), ('BEAT_THE_STREET', 'BEAT_THE_STREET'), ('QUIZ_MARVEL', 'QUIZ_MARVEL'), ('SODA_POP', 'SODA_POP'), ('ROADIES', 'ROADIES'), ('MASQUERADE_PARTY', 'MASQUERADE_PARTY'), ('STUDENT_OF_THE_YEAR_2', 'STUDENT_OF_THE_YEAR_2'), ('CELEBRITY_NIGHT', 'CELEBRITY_NIGHT'), ('STUDENT_OF_THE_YEAR_3', 'STUDENT_OF_THE_YEAR_3'), ('TALENT_FIESTA', 'TALENT_FIESTA'), ('GUESS_THE_NAME', 'GUESS_THE_NAME'), ('AWAKENINGS_DJ_2', 'AWAKENINGS_DJ_2'), ('MURDER_MYSTERY', 'MURDER_MYSTERY'), ('BOLLYWOOD_PARTY', 'BOLLYWOOD_PARTY'), ('STUDENT_OF_THE_YEAR_4', 'STUDENT_OF_THE_YEAR_4'), ('OPEN_MIC_2', 'OPEN_MIC_2'), ('VOGUE', 'VOGUE'), ('STAGE_PERFORMANCES', 'STAGE_PERFORMANCES'), ('EDM_NIGHT', 'EDM_NIGHT')], max_length=40)),
                ('registrations', models.IntegerField()),
            ],
        ),
    ]
